### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by MarkoNS1990**
In this project, we were making a clone of NY Times article page using knowledge of positionining and floating elements mostly done with flex.

### CODE REVIEW

**Review by Temmarie — CHANGES_REQUESTED** [review]
## STATUS: INVALID! :exclamation:
### Hi @MarkoNS1990  ! :wave: :wave:

#### Hello there, You've done a good job so far, however, I have to mark your project as invalid. Please make the changes as listed below.

- [x] The project has a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).
- Your readme is currently just a copy and paste template. You need to customize it to include your personal information, a screenshot of the project as well as a summary about the project and other parts mentioned in the template.

- [x] Pull Request has a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).
- You currently have no message in your Pull Request. Be sure to add a summary of what was required in this project. For example, "In this project, we were required to make a clone of the New York Times article page ..."

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Invalid Submission :x: :disappointed: :stop_sign: 
## Hello @MarkoNS1990    :handshake: :handshake: :handshake: 

Thank you for submitting a code review request. And congratulations on that you have completed this project. However your code review request is marked as invalid due to the following reasons:

1. As mentioned with the previous reviewer, please customize the readme file with your information which regards this project. For example in the description section, add a description of this project, in the setup section add how to get this project on local computer and how to run it.

Happy coding!!!
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by mimipeshy** [comment]
### STATUS: CHANGES REQUIRED 🔴 ♻️ 

Hello @MarkoNS1990, 👋🏾 👋🏾 Thank you for making the mandatory changes the former reviewer mentioned. 👍🏾 👍🏾 
A lot of effort surely went into this and you did well. Let's make it even better 🛠️ 

#### Page structure

##### Navigation bar


- [ ]  It has a "Hamburger button", a search icon, and a link with text on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
**Original**

image
- [ ]  The NY Times logo is a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))

- [ ] Add more social media handles to the author's section
- [ ] Avoid inline CSS styling `index.html line 42,46,88,150,196,197` because as your project gets bigger it becomes difficult to debug plus we want to keep HTML as clean as possible so move all styling to style.css file.


That's all :smile: kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, or just comment on this PR and tag my name and I will be glad to help_
Regards
Peris Ndanu

**Review by PhillipUg — APPROVED** [review]
# Status: Project Approved! 🥇 
Congratulations on implementing all requirements and getting this project approved. :+1:

You can merge this branch into the development branch when you're ready and go on to your next project.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime** or
 <a href="mailto:phillipmusiime@gmail.com"> gmail</a> &nbsp; &nbsp; [Twitter Follow](https://twitter.com/intent/follow?screen_name=Phillip_Ug) &nbsp; &nbsp; [GitHub followers](https://github.com/PhillipUg)

**Pull request merged**
